nodeLinker: node-modules
# npmRegistries:
#   "https://npm.pkg.github.com":
#     npmAuthToken: "${GITHUB_TOKEN}"
#     npmAlwaysAuth: true

# npmScopes:
#   getlivo:
#     npmRegistryServer: "https://npm.pkg.github.com"
